### ISSUE TITLE
Grab Baltimore NAIP imagery and add to repo

### ISSUE THREAD

**Issue by alexkapps** [KAPPS-/maptime_hrva#1]
@albert-decatur @MirandaLv 

http://www.fsa.usda.gov/FSA/apfoapp?area=home&subject=prog&topic=nai

**Comment by albert-decatur** [comment]
imagery here -it's a mrsid converted to tif for new qgis user convenience:
https://drive.google.com/file/d/0B5eSuD_FC6SiOFctY1I1WHpyRmM/view?usp=sharing
